name: Build Lunar Info Card

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Lunar Info Card
        run: npm run build

      - name: Commit built JS to root
        run: |
          git config --global user.name "hzonz"
          git config --global user.email "hzonz@outlook.com"
          git add lunar-info-card.js
          git commit -m "Auto-build Lunar Info Card [skip ci]" || echo "No changes to commit"
          git push
